version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: omniauth
    versions:
    - 2.0.2
    - 2.0.3
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
  - dependency-name: puma
    versions:
    - 3.12.6
    - 5.2.0
    - 5.2.1
  - dependency-name: ffaker
    versions:
    - 2.17.0
  - dependency-name: rack-attack
    versions:
    - 6.4.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: sprockets
    versions:
    - 4.0.2
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: rake
    versions:
    - 13.0.3
  - dependency-name: websocket-extensions
    versions:
    - 0.1.5
  - dependency-name: rails-html-sanitizer
    versions:
    - 1.3.0
